language: c

compiler:
        - clang
        - gcc

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq libsystemd-daemon-dev

dist: trusty
sudo: required

script:
        - autoreconf -i && ./configure && make
