language: c

compiler:
        - clang
        - gcc

before_install:
        - echo "deb http://archive.ubuntu.com/ubuntu wily main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
        - sudo apt-get update -qq
        - sudo apt-get install -qq libsystemd-daemon-dev

dist: trusty
sudo: required

script:
        - autoreconf -i && ./configure && make
